### ISSUE TITLE
No targets specified and no makefile found

### ISSUE THREAD

**Issue by ghost** [compass-rs/sass-rs#63]
~~~
   Compiling sass-sys v0.4.15 (C:\sass-rs-master\sass-sys)
error: failed to run custom build command for `sass-sys v0.4.15
(C:\sass-rs-master\sass-sys)`

Caused by:
  process didn't exit successfully: `C:\sass-rs-master\target\debug\build\
  sass-sys-1bbb3f9bc67897ff\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Build error:
STDERR:make: *** No targets specified and no makefile found.  Stop.

STDOUT:', sass-sys\build.rs:93:9
~~~

**Comment by cup** [comment]
https://github.com/getzola/zola/issues/918

**Comment by Keats** [comment]
I think this error is due to https://github.com/compass-rs/sass-rs/pull/61

**Comment by cup** [comment]
https://github.com/getzola/zola/issues/893

**Comment by cup** [comment]
Should this be working now? I tried again briefly but still no luck

**Comment by Keats** [comment]
this should be working yes, make sure you have the latest master

**Comment by cup** [comment]
No, it still doesnt work. I can compile libsass no problem:

~~~
git clone git://github.com/sass/libsass
cd libsass
AR=x86_64-w64-mingw32-ar \
CC=x86_64-w64-mingw32-gcc \
CXX=x86_64-w64-mingw32-g++ \
make
~~~

but if I turn around and try with sass-rs:

~~~
git clone git://github.com/compass-rs/sass-rs
cd sass-rs
AR=x86_64-w64-mingw32-ar \
CC=x86_64-w64-mingw32-gcc \
CXX=x86_64-w64-mingw32-g++ \
../Rust/bin/cargo build
~~~

it fails:

~~~
error: failed to run custom build command for
   `sass-sys v0.4.16 (C:\sass-rs\sass-sys)`

Caused by:
process didn't exit successfully: `C:\sass-rs\target\debug\build\
   sass-sys-31542ac7be5154b6\build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=C:\sass-rs\target\debug\build\
   sass-sys-fb08bcd006a7e2d0\out\build\lib
cargo:rustc-link-lib=static=sass

--- stderr
thread 'main' panicked at ': Os { code: 2, kind: NotFound, message: "The system
   cannot find the file specified." }', src\libcore\result.rs:1165:5
~~~

**Comment by cup** [comment]
Heres something interesting. Running with `RUST_BACKTRACE=full` gives:

~~~
16:           0x4047d8 - build_script_build::compile::{{closure}}::hd021d0f19a493dff
                         at sass-sys/build.rs:90
~~~

which gives:

https://github.com/compass-rs/sass-rs/blob/3f5e5733fcb84fa7866db9713dea4f851eac20c6/sass-sys/build.rs#L90

not sure if that should be hardcoded like that, pulling from environment
variable `CC` would be better.

**Comment by Keats** [comment]
I think you might need clang? `CC` is not necessarily set in the environment, at least not on my computer.

**Comment by cup** [comment]
The point is with some systems the `cc` executable doesnt exist. For example on
my system (Windows), the compiler is `x86_64-w64-mingw32-gcc.exe`.

Not sure how much experience you have with C/C++, but typical build systems from
that world will call the compiler from the environment variables `CC`/`CXX`
first, then if those fail fall back to default executable `cc`.

If you dont do that, youre locking users out who dont have that executable, or
forcing them to do a symlink which is less desirable solution.

**Comment by Keats** [comment]
> Not sure how much experience you have with C/C++

Absolutely none!
Can you do a PR for that? The build only covers msvc on Windows currently since it's what I use on CI, not mingw32

**Comment by cup** [comment]
Well it looks to be pointless for me to fix this now. But I will put my progress
here. So first I did this:

~~~diff
--- a/sass-sys/build.rs
+++ b/sass-sys/build.rs
@@ -87,7 +87,8 @@ fn compile() {
         || target.contains("netbsd")
         || target.contains("openbsd");
     let libprobe = | lib: &str | -> bool {
-      Command::new("cc")
+      let r = env::var("CC").unwrap_or("cc".to_string());
+      Command::new(&r)
         .arg("-xc++")
~~~

but then I get this:

~~~
Compiling sass-rs v0.2.2 (C:\sass-rs)
error: linking with `gcc` failed: exit code: 1
~~~

So looking here:

https://zork.net/~st/jottings/rust-windows-and-debian.html

I create `C:\Users\Steven\.cargo\config` with:

~~~
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
~~~

and get:

~~~
Compiling sass-rs v0.2.2 (C:\sass-rs)
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
~~~

which is better, but also this:

~~~
json.cpp:(.text.unlikely+0x34): undefined reference to `__imp___acrt_iob_func'
~~~

which seems to be a known and old Rust issue:

https://github.com/rust-lang/rust/issues/47048

looks like a fix is in progress:

https://github.com/rust-lang/rust/pull/67429

until when, maybe Zola could use one of these instead:

- https://github.com/kaj/rsass
- https://github.com/mpg-tomoya-komiyama/sassruist
- https://github.com/ConnorSkees/grass

or perhaps have an option to disable Sass? Personally I dont even use Sass,
which makes it that much more frustrating.

**Comment by Keats** [comment]
I'm looking forward to https://github.com/kaj/rsass but it needs to be more complete to replace sass-rs.
I would recommend sticking to pre-built binaries of Zola but if you want to disable Sass, it's pretty self-contained so that's easy to keep the change in a local fork: it's all in components/site/src/lib.rs

**Comment by cup** [comment]
I need a new Zola build to take advantage of the fix here:

https://github.com/getzola/zola/issues/893

but as Zola doesnt have artifact on the CI, I have to build my own. It would be preferable if Zola had option to disable Sass at build time. I can file issue if thats acceptable.

**Comment by Keats** [comment]
It could be a default feature that some users can disable if they need to. Feel free to create an issue for that, I don'tt think artifacts will be created in the CI.

**Comment by cup** [comment]
https://github.com/getzola/zola/issues/930

**Comment by cup** [comment]
https://github.com/rust-lang/rust/issues/68872
